version: '3.5'
services:
  mysql:
    image: mysql:latest
    restart: always
    container_name: "mysql"
    volumes:
      - "./db:/var/lib/mysql"
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=
      - MYSQL_USER=brs-
      - MYSQL_PASSWORD=
  web:
    build: .
    links:
      - mysql
    container_name: BRS-Service
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - DB_PORT=3306
      - DB_NAME=
      - DB_HOST=
      - MYSQL_USER=b
      - MYSQL_USER_PASSWORD=
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - mysql