name: Build and push image to ECR
on: push
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build and run tests
        run: mvn test -DskipTags=db
  build_deploy:
    needs: run_tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - uses: aws-actions/amazon-ecr-login@v1
        id: login-ecr

      - name: Build and push image
        id: build_image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.REPO_NAME }}
          IMAGE_TAG: ${{ github.run_number }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      - uses: actions/checkout@v2
      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Decode kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig

      - name: Helm deploy
        uses: deliverybot/helm@v1
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.REPO_NAME }}
          IMAGE_TAG: ${{ github.run_number }}
        with:
          args: >
            repo add external-secrets https://charts.external-secrets.io &&
            repo update &&
            upgrade --install external-secrets external-secrets/external-secrets
              --namespace external-secrets
              --create-namespace
              --set installCRDs=true
              --set rbac.create=false
              --wait &&
            upgrade --install my ./nebotaskchart
              --set image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
              --set externalSecretsOperator.roleArn=${{ secrets.roleArnSecrets }}
              --set asg.asgRoleArn=${{ secrets.roleArnASG }}

          release: ''
          namespace: ''
          chart: ''